### ISSUE TITLE
Error: Api is not returning

### ISSUE THREAD

**Issue by victorwolff** [meruff/go-trailhead-leaderboard-api#10]
Hi, when i try to access the API im getting 
{"error":"Could not find Trailhead ID for user: 'vwolff'. Does this profile exist? Is it set to public?"}{"error":"Could not find valid User for this handle."}

**Comment by meruff** [comment]
Hi @victorwolff, please see #4, #7, and the open pull request #9. We know about this and are currently working on it.

**Comment by PaulWeakley** [comment]
@meruff @victorwolff In testing the changes for the FwUID, This defect still exists and is not the FwUID error. However, it is related to the profile app's aura context. Working on a fix for both issues.

**Comment by PaulWeakley** [comment]
This was not related to the Aura config as I thought but is related to fetching the user's ID and Salesforce switching from an "uid" to "cuid" field in different scenarios.

Still working on fix.
