### ISSUE TITLE
Support Certifications

### ISSUE THREAD

**Issue by raphaelbarreiros** [meruff/go-trailhead-leaderboard-api#2]
Salesforce just released Certifications on your trailblazer.me profile. Please consider supporting it :)

**Comment by meruff** [comment]
@raphabarreiros fixed in 73660bf.

https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/raphaelbarreiros/certifications

Also, congrats on all your certs!

**Comment by raphaelbarreiros** [comment]
@meruff wow! That was quick !!! Thanks a lot !
Thank you! ☺️😉
